// app/(client)/layout.tsx
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import AuthWrapper from "./authWrapper";

export const metadata: Metadata = {
  title: "LIÊN HỆ - GIÁM ĐỊNH BẢO MINH",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper
      allowedRoles={[
        "SERVICE_MANAGER",
        "ADMIN",
        "IMPORTER",
        "DOCUMENT_STAFF",
        "ISO_STAFF",
      ]}
    >
      {children}
      <Toaster position="top-right" reverseOrder={false} />
    </AuthWrapper>
  );
}
