import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import AuthWrapper from "../(client)/authWrapper";

export const metadata: Metadata = {
  title: "BMI Dashboard - GIÁM ĐỊNH BẢO MINH",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper
      allowedRoles={[
        "ADMIN",
        "IMPORTER",
        "DOCUMENT_STAFF",
        "ISO_STAFF",
      ]}
    >
      {children}
      <Toaster position="top-right" reverseOrder={false} />
    </AuthWrapper>
  );
}
